version: "2"
services:
  app:
    build: ./app
    links:
      - db
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports: ["5000:5000"]
    volumes: ["./app:/app"]

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  web:
    command: yarn dev
    links:
      - app
    environment:
      REACT_APP_API_URI: http://localhost:5000
    image: node
    ports:
      - 3030:3000
    volumes:
      - ./web:/www
    working_dir: /www
